export const dataTypes = {
    Email: "SingleLine.Email",
    Phone: "SingleLine.Phone",
    Text: "SingleLine.Text",
    TextArea: "SingleLine.TextArea",
    Ticker: "SingleLine.Ticker",
    URL: "SingleLine.URL",
    Boolean: "TwoOptions",
    LongText: "Multiple",
    Lookup: "Lookup.Simple",
    MultiSelectPicklist: "MultiSelectPicklist",
    OptionSet: "OptionSet",
    Currency: "Currency",
    DateAndTime: "DateAndTime.DateAndTime",
    DateOnly: "DateAndTime.DateOnly",
    Decimal: "Decimal",
    Enum: "Enum",
    FP: "FP",
    Object: "Object",
    Whole: "Whole.None",
} as const

